name: amphitheatre
description: Open source Flutter-based application that enables you to interact with Amphitheatre.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  colorize_text_avatar: ^1.0.2
  empty_widget: ^0.0.5
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  provider: ^6.0.3
  time: ^2.1.0
  window_manager: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  
  # Enable generation of localized Strings from arb files.
  generate: true
  
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
