name: Tests

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'
      - '.github/ISSUE_TEMPLATE/**'
      - .github/PULL_REQUEST_TEMPLATE.md
  pull_request:
    paths-ignore:
      - '*.md'
      - '.github/ISSUE_TEMPLATE/**'
      - .github/PULL_REQUEST_TEMPLATE.md

# Declare default permissions as read only.
permissions: read-all

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: stable
      - run: flutter doctor -v

      # Checkout code and get packages.
      - name: Checkout code
        uses: actions/checkout@v3
      - run: flutter pub get

      - name: Run code generation
        run: flutter pub run build_runner build
        
      # Analyze, check formatting, and run unit tests.
      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .
      - name: Run Flutter unit tests
        run: flutter test